### ISSUE TITLE
Link to docs is broken

### ISSUE THREAD

**Issue by dawoodjee** [Monogramm/frappe_pwa#8]
![image](https://user-images.githubusercontent.com/7912989/116811268-be156400-ab48-11eb-8113-e2ee17d0d775.png)

https://monogramm.github.io/frappe_pwa/

This link doesnt go anywhere

**Comment by madmath03** [comment]
Thanks @dawoodjee . Just enabled GitHub Pages. Link is working now.

**Comment by dawoodjee** [comment]
Thanks @madmath03 

Found a bunch of broken links trying to follow the docs, please try clicking through as a test to verify

**Comment by madmath03** [comment]
> Found a bunch of broken links trying to follow the docs, please try clicking through as a test to verify

If you mean the links from the [app documentation](https://github.com/Monogramm/frappe_pwa/blob/master/frappe_pwa/docs/index.md), sadly that's "_normal_" because it's designed to be generated using [recod_frappe_devtools](https://github.com/Monogramm/recod_frappe_devtools) which is a fork / fix of Frappe's (former) documentation mechanism and unfortunately does not use relative links (menu, images).

Fixed the contributing link though
